### ISSUE TITLE
Is it possible to using colon and comma in template?

### ISSUE THREAD

**Issue by iozcelik** [lunet-io/scriban#263] opened 2020-11-23 07:10 UTC
In liquid, normally using colon and comma to determine filter arguments.

For example: {{ "This is an example" | replace: "an", "a" }}

However in scriban: {{ "This is an example." | string.replace "an" "a" }}

Using like that not understandable, you need to look closer for space. If I have any chance to change the space with comma and also add a colon. I prefer this usage.

Why I need to ask this, because I cannot use LiquidParse below code.

```
var template = Template.Parse("{{ 'Hello World' | string.replace 'World' name }}");
var result = template.Evaluate(new { Name = "Mars" });
```

**Comment by xoofx** [comment] 2020-11-23 07:25
This is by design and can't be changed in Scriban. Also Liquid had never specified the way arguments would be parsed, so that's why it was not implemented in Scriban (Liquid support is not a full Liquid support, more a support to help transitioning)

**Comment by iozcelik** [comment] 2020-11-23 07:32
Thanks for quick reply. So why I cannot use Evaluate with LiquidParse? It is thrown exception. However, render is working expected.

Exception:` Scriban.Syntax.ScriptRuntimeException: '<input>(1,20) : error : The function `replace` was not found'`

**Comment by xoofx** [comment] 2020-11-23 07:59
Oh, right, for the second issue, Evaluate is currently assuming Scriban language. It's a bug (Internally it has to use "LiquidTemplateContext` not `TemplateContext`)

**Comment by xoofx** [comment] 2020-11-30 19:39
This should be fixed (the usage of Liquid functions in Template.Evaluate) in the next release `3.0.4`

**Closed by xoofx** 2020-11-30 19:39 UTC
Labels: bug
